exp_name: base_model

model:
  LSTM_units: [64, 64]
  LSTM_dropout_rates: [null, null]
  eval_units: 64
  eval_dropout_rate: 0.2
  output_units: 1
  l2_factor: 0.000000001

train:
  optimizer:
    learning_rate: 0.00001
  loss:
    main_output: "binary_crossentropy"
    aux_output: "binary_crossentropy"
  loss_weights:
    main_output: 1
    aux_output: 0.5
  metrics:
    main_output: "accuracy"
    aux_output: "accuracy"
