metadata:
  experiment: 20230306-d3_rot-surf_biased-noise
  run: example-train
  init_weights: null

dataset:
  train:
    shots: 200000
    rounds: !range [1, 20, 2]
    states: ["000000000", "111111111"]

  dev:
    shots: 20000
    rounds: !range [1, 20, 2]
    states: ["000000000", "111111111"]

  test:
    shots: 5000
    rounds: !range [1, 20, 2]
    states: ["000000000", "111111111"]

  rot_basis: false
  folder_format_name: "surf-code_d3_b{basis}_s{state}_n{shots}_r{num_rounds}"
  input: "defects"

train:
  optimizer:
    learning_rate: 0.0001
  loss:
    main_output: binary_crossentropy
    aux_output: binary_crossentropy
  loss_weights:
    main_output: 1.0
    aux_output: 0.5
  metrics:
    main_output: accuracy
    aux_output: accuracy
  callbacks:
    early_stop:
      monitor: val_loss
      mode: min
      min_delta: 0
      patience: 10
    csv_log:
      append: false
    checkpoint:
      monitor: val_loss
      mode: min
      save_best_only: true

  epochs: 500
  batch_size: 64

model:
  rec_encoder: null
  eval_encode: null
  ConvLSTM:
    filters: [64, 64]
    dropout_rates: [null, null]
    kernel_sizes: [2, 2]
  LSTM:
    units: [64, 64]
    dropout_rates: [null, null]
  rec_decoder: null
  eval_decoder: null
  main_eval:
    units: [64, 1]
    dropout_rates: [null, null]
    l2_factor: null
  aux_eval:
    units: [64, 1]
    dropout_rates: [null, null]
    l2_factor: null
