metadata:
  experiment: 20230217-d3_rot-surf_simulated_google
  run: google_simulated_eval-dr0-05
  prev_run: null

dataset:
  train:
    shots: 400000
    rounds: !range [1, 20, 2]

  dev:
    shots: 40000
    rounds: !range [1, 20, 2]

  rot_basis: false
  lstm_input: "defects"
  eval_input: "defects"
  folder_format_name: "surface_code_b{rot_basis}_d3_r{num_rounds:02d}_center_3_5"

train:
  optimizer:
    learning_rate: 0.0005
  loss:
    main_output: binary_crossentropy
    aux_output: binary_crossentropy
  loss_weights:
    main_output: 1.0
    aux_output: 0.5
  metrics:
    main_output: accuracy
    aux_output: accuracy
  callbacks:
    early_stop:
      monitor: val_loss
      mode: min
      min_delta: 0
      patience: 10
    csv_log:
      append: false
    checkpoint:
      monitor: val_loss
      mode: min
      save_best_only: true

  epochs: 500
  batch_size: 64

model:
  LSTM_units: [64, 64]
  LSTM_dropout_rates: [null, null]
  eval_units: 64
  eval_dropout_rate: 0.05
  output_units: 1
  l2_factor: null
