metadata:
  experiment: 20230131-d3_rot-surf_circ-level_large-dataset
  run: example-train
  prev_run: null

dataset:
  train:
    shots: 200000
    rounds: !range [1, 20, 2]
    states: [0, 1]

  dev:
    shots: 20000
    rounds: !range [1, 20, 2]
    states: [0, 1]

  rotate_basis: false
  sequential_input: "defects"
  non-sequential_input: "defects"

train:
  optimizer:
    learning_rate: 0.00001
  loss:
    main_output: binary_crossentropy
    aux_output: binary_crossentropy
  loss_weights:
    main_output: 1.0
    aux_output: 0.5
  metrics:
    main_output: accuracy
    aux_output: accuracy
  callbacks:
    early_stop:
      monitor: val_loss
      mode: min
      min_delta: 0
      patience: 50
    csv_log:
      append: false
    checkpoint:
      monitor: val_loss,
      mode: min
      save_best: true

  num_epochs: 500
  batch_size: 64

model:
  LSTM_units: [64, 64]
  LSTM_dropout_rates: [null, null]
  eval_units: 64
  eval_dropout_rate: 0.2
  output_units: 1
  l2_factor: 0.000000001
